        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:34 2017
        MODULE FLEXEFT_DISC__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_DISC
              USE BIO_MOD
            END SUBROUTINE FLEXEFT_DISC
          END INTERFACE 
        END MODULE FLEXEFT_DISC__genmod
