        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:32 2017
        MODULE NPPZDD_MOD__genmod
          INTERFACE 
            SUBROUTINE NPPZDD_MOD
              USE BIO_MOD
            END SUBROUTINE NPPZDD_MOD
          END INTERFACE 
        END MODULE NPPZDD_MOD__genmod
