        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:33 2017
        MODULE NPZD_DISC__genmod
          INTERFACE 
            SUBROUTINE NPZD_DISC
            END SUBROUTINE NPZD_DISC
          END INTERFACE 
        END MODULE NPZD_DISC__genmod
