        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:03 2017
        MODULE FLEXEFT_SIMPLE__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_SIMPLE
            END SUBROUTINE FLEXEFT_SIMPLE
          END INTERFACE 
        END MODULE FLEXEFT_SIMPLE__genmod
