        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:01 2017
        MODULE FLEXEFT_2SP__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_2SP
              USE BIO_MOD
            END SUBROUTINE FLEXEFT_2SP
          END INTERFACE 
        END MODULE FLEXEFT_2SP__genmod
