        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:33 2017
        MODULE GEIDER_SIMPLE__genmod
          INTERFACE 
            SUBROUTINE GEIDER_SIMPLE
            END SUBROUTINE GEIDER_SIMPLE
          END INTERFACE 
        END MODULE GEIDER_SIMPLE__genmod
