        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:31 2017
        MODULE NPZD_2SP__genmod
          INTERFACE 
            SUBROUTINE NPZD_2SP
              USE BIO_MOD
            END SUBROUTINE NPZD_2SP
          END INTERFACE 
        END MODULE NPZD_2SP__genmod
