        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 10 17:23:01 2017
        MODULE CHOOSE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CHOOSE_MODEL
            END SUBROUTINE CHOOSE_MODEL
          END INTERFACE 
        END MODULE CHOOSE_MODEL__genmod
