        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 10 17:23:03 2017
        MODULE FLEXEFT_DISC__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_DISC
              USE BIO_MOD
            END SUBROUTINE FLEXEFT_DISC
          END INTERFACE 
        END MODULE FLEXEFT_DISC__genmod
