        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 10 17:23:03 2017
        MODULE FLEXEFT_SIMPLE__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_SIMPLE
            END SUBROUTINE FLEXEFT_SIMPLE
          END INTERFACE 
        END MODULE FLEXEFT_SIMPLE__genmod
