        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 10 17:23:02 2017
        MODULE GEIDER_DISC__genmod
          INTERFACE 
            SUBROUTINE GEIDER_DISC
            END SUBROUTINE GEIDER_DISC
          END INTERFACE 
        END MODULE GEIDER_DISC__genmod
