        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 10 17:23:02 2017
        MODULE GEIDER_SIMPLE__genmod
          INTERFACE 
            SUBROUTINE GEIDER_SIMPLE
            END SUBROUTINE GEIDER_SIMPLE
          END INTERFACE 
        END MODULE GEIDER_SIMPLE__genmod
