        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 10 17:23:00 2017
        MODULE NPZD_N2__genmod
          INTERFACE 
            SUBROUTINE NPZD_N2
            END SUBROUTINE NPZD_N2
          END INTERFACE 
        END MODULE NPZD_N2__genmod
