        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:31 2017
        MODULE FLEXEFT_2SP__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_2SP
              USE BIO_MOD
            END SUBROUTINE FLEXEFT_2SP
          END INTERFACE 
        END MODULE FLEXEFT_2SP__genmod
