        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:33 2017
        MODULE GEIDER_DISC__genmod
          INTERFACE 
            SUBROUTINE GEIDER_DISC
            END SUBROUTINE GEIDER_DISC
          END INTERFACE 
        END MODULE GEIDER_DISC__genmod
