        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:04 2017
        MODULE EFT_PPZDD_MOD__genmod
          INTERFACE 
            SUBROUTINE EFT_PPZDD_MOD
              USE BIO_MOD
            END SUBROUTINE EFT_PPZDD_MOD
          END INTERFACE 
        END MODULE EFT_PPZDD_MOD__genmod
