        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:32 2017
        MODULE CHOOSE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CHOOSE_MODEL
            END SUBROUTINE CHOOSE_MODEL
          END INTERFACE 
        END MODULE CHOOSE_MODEL__genmod
