        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 13 17:24:33 2017
        MODULE FLEXEFT_SIMPLE__genmod
          INTERFACE 
            SUBROUTINE FLEXEFT_SIMPLE
            END SUBROUTINE FLEXEFT_SIMPLE
          END INTERFACE 
        END MODULE FLEXEFT_SIMPLE__genmod
