        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:02 2017
        MODULE NPPZDD_MOD__genmod
          INTERFACE 
            SUBROUTINE NPPZDD_MOD
              USE BIO_MOD
            END SUBROUTINE NPPZDD_MOD
          END INTERFACE 
        END MODULE NPPZDD_MOD__genmod
