        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:02 2017
        MODULE CHOOSE_MODEL__genmod
          INTERFACE 
            SUBROUTINE CHOOSE_MODEL
            END SUBROUTINE CHOOSE_MODEL
          END INTERFACE 
        END MODULE CHOOSE_MODEL__genmod
