        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:03 2017
        MODULE GEIDER_SIMPLE__genmod
          INTERFACE 
            SUBROUTINE GEIDER_SIMPLE
            END SUBROUTINE GEIDER_SIMPLE
          END INTERFACE 
        END MODULE GEIDER_SIMPLE__genmod
