        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:03 2017
        MODULE GEIDER_DISC__genmod
          INTERFACE 
            SUBROUTINE GEIDER_DISC
            END SUBROUTINE GEIDER_DISC
          END INTERFACE 
        END MODULE GEIDER_DISC__genmod
