        !COMPILER-GENERATED INTERFACE MODULE: Tue May  2 15:02:01 2017
        MODULE NPZDPHY_SIZE__genmod
          INTERFACE 
            SUBROUTINE NPZDPHY_SIZE(PMU,NO3,TC,PAR_,MUNET,SI,LNO3)
              REAL(KIND=8), INTENT(IN) :: PMU
              REAL(KIND=8), INTENT(IN) :: NO3
              REAL(KIND=8), INTENT(IN) :: TC
              REAL(KIND=8), INTENT(IN) :: PAR_
              REAL(KIND=8), INTENT(OUT) :: MUNET
              REAL(KIND=8), INTENT(OUT) :: SI
              REAL(KIND=8), INTENT(OUT) :: LNO3
            END SUBROUTINE NPZDPHY_SIZE
          END INTERFACE 
        END MODULE NPZDPHY_SIZE__genmod
